sudo: required
dist: bionic
language: java
jdk:
    - oraclejdk11
python:
    - "3.6"
services: docker
before_install:
    - sudo apt-get update
    #- cd 17\ RestWithSpringBootUdemy\ Docker/
    #- cd Deploy/
    - cd ./RestWithSpringBootUdemy/
    - echo "Let's start Maven Package!"
    - mvn clean package
    - cd ..
    #- echo "We are in the docker folder!"
script:
    - echo "Ok here we GO!"
    - docker-compose build
before_deploy:
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
    provider: script
    script: 
        docker tag rest-with-spring-boot-udemy:latest italogouveia2/rest-with-spring-boot-udemy:$TRAVIS_JOB_ID
        docker push italogouveia2/rest-with-spring-boot-udemy:$TRAVIS_JOB_ID;
    on:
        branch: master
after_success:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - python3 -V
    - pip3 -V 
    - pip3 uninstall wheel
    - pip3 install wheel
    - pip3 install awscli --upgrade --user
    - export PATH=$PATH:$HOME/.local/bin
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URL
    - docker tag italogouveia2/rest-api-spring-udemy:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
    - docker push $IMAGE_REPO_URL:$TRAVIS_JOB_ID
    # Parte abaixo pode ser substituida pelo comentário ao final porém a parte abaixo possui muito mais recursos para o deploy
    - echo "Docker image OK!"
    - sudo add-apt-repository ppa:eugenesan/ppa --force-yes
    - sudo apt-get update
    - sudo apt-get install jq -y
    - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
    - sudo chmod +x /usr/bin/ecs-deploy
    - echo "AWS ECS-Deploy Setup is Configured"
    - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
    #asw ecs update-service --service $SERVICE_NAME --task-definition $TASK_NAME force deploy
notifications:
    email: false