#docker-compose up -d --build to build the container and startup
#docker login docker.io login on docker hub
#docker push italogouveia2/rest-with-spring-boot to push the docker image
#docker images to consult the images that you have
version: '3.4'
services:
    db:
        image: italogouveia2/mysql-rest-with-spring-boot
        #opção de autenticação legada no mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: rest_with_spring_boot_udemy
        ports:
            - "3308:3306"
        networks: 
            - udemy-network
    rest-with-spring-boot-udemy:
        image: italogouveia2/rest-with-spring-boot
        restart: always
        build: ./RestWithSpringBootUdemy
        working_dir: /RestWithSpringBootUdemy
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes:
            - ./RestWithSpringBootUdemy:/RestWithSpringBootUdemy
            - ~/.m2:/root/.m2
        ports:
            - "8080:8080"
        command: mvn clean spring-boot:run
        links:
            - db
        depends_on: 
            - db
        networks: 
            - udemy-network
#Configuração de rede
networks:
    udemy-network:
        driver: bridge